apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-clean-template
  annotations:
    github.com/project-slug: Bilalaybar/go-clean-template
spec:
  type: other
  lifecycle: unknown
  owner: guests
